### ISSUE TITLE
Track down why confidence score is not returned from Autopilot

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#98]
![image](https://user-images.githubusercontent.com/1438064/94178083-752d5c80-fe4f-11ea-8cb4-366827c8356d.png)

**Comment by antje** [comment]
https://docs.aws.amazon.com/sagemaker/latest/dg/autopilot-automate-model-development-container-output.html

**Comment by antje** [comment]
Here is how to update the definition of the inference containers to receive predicted_labels and probability.

containers[1]['Environment'].update({'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_labels, probability'})
containers[2]['Environment'].update({'SAGEMAKER_INFERENCE_INPUT': 'predicted_labels, probability'})
containers[2]['Environment'].update({'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_labels, probability'})

**Comment by antje** [comment]
Sagemaker documentation has an error. Correct code is as follows:
(predicted_label instead of predicted_labels)

containers[1]['Environment'].update({'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_label, probability'})
containers[2]['Environment'].update({'SAGEMAKER_INFERENCE_INPUT': 'predicted_label, probability'})
containers[2]['Environment'].update({'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_label, probability'})

**Comment by antje** [comment]
Documentation has been updated:
https://docs.aws.amazon.com/sagemaker/latest/dg/autopilot-automate-model-development-container-output.html
